### ISSUE TITLE
Axis labels (in lat/lon?) for examples like dashboard.py

### ISSUE THREAD

**Issue by jbednar** [pyviz/datashader#13]
This won't be very practical right now, but it would be great to be able to show axis labels with lat, lon coordinates in degrees.  Doing this properly would require Bokeh support for nonlinear axis lines, as in:

![image](https://cloud.githubusercontent.com/assets/1695496/12492830/c5dc5154-c047-11e5-9409-c478d7297ee5.png)

but even just having the approximately correct values in degrees along the x and y axis (with no grid lines, since they would be incorrectly straight!) would be helpful in some cases.  

Meanwhile, maybe we can support hovering, to show the value in lat/lon, converted from the native Web Mercator values?

**Comment by brendancol** [comment]
axis labels will be coming soon with help from Bokeh's `TickFormatterFunc`, but is not quite there yet because the formatter only accepts one argument (for lat/lng axis labels with need both axes values to compute from meters -> lng/lat)

**Comment by jbednar** [comment]
Now available; needs testing.
