### ISSUE TITLE
Using xarray.dataset as input

### ISSUE THREAD

**Issue by jsignell** [pyviz/datashader#201]
It seems like it should be straightforward to add xarray.dataset as an input option to datashader. If the capability is already there, then maybe just adding a sentence or two to the docs would do it. 

I have an example with a work-around here in box 7: http://nbviewer.jupyter.org/gist/jsignell/a6bf9d8545837e18dcf8fef66d556a76

**Comment by brendancol** [comment]
@jsignell right now, I would reduce the `xarray.Dataset` to an `xarray.DataArray` and then you can pass it to the relevant transfer_function.  Basically you are skipping the aggregation stage correct?

**Comment by jsignell** [comment]
I'm not sure I understand. I can reduce to a `xarray.DataArray` but I still don't see how to pass it to the transfer function. I am aggregating by count.

**Comment by brendancol** [comment]
@jsignell so if you have a DataArray which represents count, then you can pass it like so to get an output image:
```
img = tf.interpolate(my_data_array, cmap=viridis, how='linear')
```

**Comment by jsignell** [comment]
But isn't that kind of the point of datashader that it can do the aggregation dynamically for me? This is what I was hoping to do:

    cvs = ds.Canvas(plot_width=400, plot_height=400)
    agg = cvs.points(my_data_array, 'lon', 'lat', ds.count('lat'))
    img = tf.interpolate(agg, cmap=['lightblue', 'darkblue'], how='log')

In this case lat on lon are coords.

**Comment by jbednar** [comment]
Sounds like you want to re-rasterize already rasterized data?  If rasterio can import xarray data, seems like that would solve the issue (see the landsat example, where it starts with rasterized TIFF data).  If not, maybe the xarray data can be converted into something rasterio can handle?  Sounds annoying, though.

**Comment by jsignell** [comment]
It's not rasterized. It is point data. Each point has a lat, lon, and time.  This should be very similar to the examples that you showed in your SciPy talk.

**Comment by jbednar** [comment]
Oh, that's much easier.  You just want to use xarray as your dataframe, then.  For now you'll need to convert it to a dataframe type that we understand (Pandas or Dask), but you're right that we should consider supporting xarray for that purpose.

**Comment by jsignell** [comment]
Awesome! I know you guys are in active development, datashader is just such a good idea that I want to start using it immediately!

**Comment by jbednar** [comment]
@jcrist, how hard would it be to support xarray-based dataframes?

**Comment by jsignell** [comment]
It might just be equivalent to doing this:

    import dask.dataframe as dd
    import dask.array as da
    df = dd.from_dask_array(da.stack([dsx.lat.data, dsx.lon.data], axis=1), \
                            columns=['lat','lon'])

where `dsx` is an object of type `xarray.dataset`

**Comment by jcrist** [comment]
What are your `coords`/`dims` on your DataArray? If it's organized as point data, is there a reason for using `xarray` instead of pandas/dask dataframes?

**Comment by jsignell** [comment]
The `dims` are just record (non-physical), and the `coords` are lat, lon, and time. I am using `xarray` because the data are in NetCDF files.

**Comment by jcrist** [comment]
Does the following look like your dataset at all?

```python
In [43]: df = pd.DataFrame({'lat': np.arange(10),
   ....:                    'lon': np.arange(10, 20),
   ....:                    'time': np.arange(20, 30)})

In [44]: xdf = xr.Dataset.from_dataframe(df)

In [45]: xdf
Out[45]:
<xarray.Dataset>
Dimensions:  (index: 10)
Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 9
Data variables:
    lat      (index) int64 0 1 2 3 4 5 6 7 8 9
    lon      (index) int64 10 11 12 13 14 15 16 17 18 19
    time     (index) int64 20 21 22 23 24 25 26 27 28 29

In [46]: xdf.to_dataframe()
Out[46]:
       lat  lon  time
index
0        0   10    20
1        1   11    21
2        2   12    22
3        3   13    23
4        4   14    24
5        5   15    25
6        6   16    26
7        7   17    27
8        8   18    28
9        9   19    29
```

**Comment by jsignell** [comment]
That is pretty much what it looks like only lat, lon, and time are all coords and there are several data_vars that describe the events. Like amplitude and strokes per strike.  I linked to a gist at the top of this thread that has a url to the real data, if that is easier.
