### ISSUE TITLE
Generate slippy-map tiles easily

### ISSUE THREAD

**Issue by jbednar** [pyviz/datashader#246]
Datashader is designed to make interactive exploration of your datasets fast and easy, without needing any precomputation, prerendering, or any other up-front cost -- it just faithfully renders your data, usually fast enough to be interactive even for quite large datasets.

However, once you are done exploring and want to share your work with a wider audience, it can be difficult to provision a Python-based server for each of the people who might want to view the data.  To make it simpler to distribute an interactive visualization for others to explore, you can set up an HTML-based image tile server, with sets of image tiles at various resolutions that are provided when needed for a particular view, without needing to run any Python code.

Here's an example for some datashader output rendered at 8Kx8K resolution and then chopped up into tiles of the right sizes:

http://www.proseandcode.co.uk/beta_gtr_viz/

This one was done using leaflet.js by reddit user IanCal (see https://www.reddit.com/r/dataisbeautiful/comments/544qig/visualizing_open_flight_data_oc/d8015yi?st=itllibf9&sh=52ef0b0c).  It would be nice if we could provide a simple method to automatically create such a slippy-map tile site, or at least provide a good example of how to do it using external tools.

Just providing a zoomable image would be a good start, but if you click in the above site you can see that it includes tooltip/hover-type information to reveal what each link corresponds to, and passing that information into such a tile server will take additional effort.

**Comment by epifanio** [comment]
Thanks for `datashader`, it is just awesome.
Maybe not exactly what you are looking for, but did you had a chance to try [`gdal2tiles`](https://gist.github.com/epifanio/fe5fff7c7d0a803ad35646f401c20e02) - The `opening` of the input file happen in the `worker_tile_details` method, it should be possible to fork the original code and adapt it to take an `xarray` as input.

**Comment by jbednar** [comment]
Implemented in https://github.com/pyviz/datashader/pull/636 ; closing.  Still needs docs and polishing, though.
