### ISSUE TITLE
Installation succeeds but cannot import datashader

### ISSUE THREAD

**Issue by ek-nath** [pyviz/datashader#307]
I install `datashader` on Windows 10 x64 using anaconda (`conda install -c bokeh datashader` and using the manual installation steps) 
The installation succeeds but when I import the library using `import datashader`, the interpreter gets stuck.

Now, when I give it a keyboard interrupt, I can see the following error:
```
In [1]: import datashader
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFD92CC43E4  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFDD414717D  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFDD5A02774  Unknown               Unknown  Unknown
ntdll.dll          00007FFDD7A90D61  Unknown               Unknown  Unknown
```

**Comment by harrispilton** [comment]
I think I have similar problems in win32. There is a new pillow (4.1.0), maybe a problem with that?

**Comment by jbednar** [comment]
Hmm; sorry to hear that!  I don't have access to that platform for testing, but if I did, I'd probably go through the imports in ``datashader/__init__.py`` one by one to see which one is the problem.

**Comment by jbednar** [comment]
Closing due to age; please reopen if currently relevant.
