### ISSUE TITLE
Can't Seem to Load the Census File

### ISSUE THREAD

**Issue by MLxMantic** [pyviz/datashader#497]
I apologize,  I haven't used parquet before.  The census snappy Parquet file is not loading for me.  Any ideas?  I am getting:

FileNotFoundError: [Errno 2] No such file or directory: 'data/census.snappy.parq'

df = dd.io.parquet.read_parquet('data/census.snappy.parq')
df = df.persist()

**Comment by jbednar** [comment]
I don't think that's specific to parquet; it's just reporting that there is no directory by that name.  Did you run the data-downloading steps listed in https://github.com/bokeh/datashader/blob/master/examples/README.md ?

**Comment by MLxMantic** [comment]
Thanks for the reply, it was user error then as I went straight to the static workbooks.  I tried following the readme file but am unable to create the virtual environment from the yml file.  I open my anaconda prompt and try to run the 

conda env create --file D:/environment.yml
and I get:
SpecNotFound: Can't process without a name
I am guessing that it wants me to create a name for the v environment,  shouldn't the yml file do that for me?  When I try to pass a name for it, such as  '-n myenv'  I get...
'PackageNotFoundError:' saying it can't find environment.yml

Any thoughts?  Thanks again!

**Comment by jbednar** [comment]
You shouldn't need a name for the environment, as that's specified in the yml file.  That's a very confusing error message, but it's what you'll get if conda can't find the .yml file at all.  You should put the .yml file in your current directory, make sure it's there, then leave off the "D:/".

**Comment by MLxMantic** [comment]
When I launch my Anaconda Prompt it says:
'(C:\Users\______\AppData\Local\Continuum\Anaconda2) C:\Users\_____>'
I have put the file in both the:
(C:\Users\______\AppData\Local\Continuum\Anaconda2)
and
C:\Users\_____>
and I am still getting the SpecNotFound: Invalid name, try the format: user/package.  I also simply copied and pasted the contents of environment.ypl from github into a text file and saved it as environment.ypl -- I am not sure if this is incorrect but I would think it shouldn't hurt anything.  Any other ideas?

Thanks again for your help.

**Comment by jbednar** [comment]
Once you have the file on disk in your current directory, try running "type environment.yml".  If it displays the contents of the file, then the conda command should succeed. If it still doesn't, we'll have to figure out what's going on...
