### ISSUE TITLE
Canvas.raster should support distributed and out-of-core regridding of dask arrays

### ISSUE THREAD

**Issue by philippjfr** [pyviz/datashader#553]
The Canvas.raster method up- or downsamples xarray DataArrays, which themselves may wrap a numpy or dask array. Since dask arrays can often be larger than can be fit into memory at one time it would be great if it could apply the resampling in a distributed and out-of-core manner. This requires loading the chunks in one by one, up- or downsampling them and then stitching them all together again. Technically it should be possible to apply this using the new ``xr.apply_ufunc`` helper but there are certain things I haven't yet fully thought through, e.g. during downsampling I believe you need to have some overlap between chunks so that the aggregation at the edges of each chunk aggregates over the edge of the next chunk and a similar solution may be required for correct interpolation during upsampling.

This is a significant chunk of work but a very well defined task and would be very useful for very large arrays.

**Comment by jbednar** [comment]
The notebook in https://anaconda.org/philippjfr/tiling_demo/notebook shows some of how to do this manually, I think...

**Comment by philippjfr** [comment]
Implemented in #762
