### ISSUE TITLE
Histograms for big data using datashader

### ISSUE THREAD

**Issue by rtmatx** [pyviz/datashader#608]
Hi,

I have this idea in my head and tried in vain to search if there is any way to do this. So I am posting the question here.

I am successful in creating datashader plots for different columns of a large dataframe with all the interactive capabilities. Right now, I can plot histogram of the entire dataset for a given column. But, is there any way to have a callback to dynamically create a histogram for the data that is in the current datashader selection or any other way that you can think of to create dynamic histogram ?

Thanks

**Comment by philippjfr** [comment]
If you're using HoloViews you can easily do this using the ``.hist`` method on the rasterized image. Basically you rasterize the Image, then compute a histogram from the Image values, and then you can still apply shading by mapping the shade function onto all images.

```python
import holoviews as hv, numpy as np
from holoviews.operation.datashader import rasterize, shade
hv.extension("bokeh")

points = hv.Points(np.random.randn(10000000, 2))
rasterize(points).hist(dimension='Count').map(shade, hv.Image)
```

If you're aggregating by a particular column in a dataframe you just declare that:

```
points = hv.Points(df, ['x', 'y'], 'some_column')
rasterize(points, aggregator='mean').hist(dimension='some_column').map(shade, hv.Image)
```

If you want the histogram as a separate plot:

```python
points = hv.Points(df, ['x', 'y'], 'some_column')
img = rasterize(points, aggregator='mean')
shade(img) + img.hist(dimension='some_column', adjoin=False)
```

If you're actually trying to compute a histogram of the raw data rather than the aggregated image, you can do this:

```python
points = hv.Points(df, ['x', 'y'], 'some_column')
range_stream = hv.streams.RangeXY()
dyn_hist = hv.DynamicMap(lambda: x_range, y_range: points.select(x=(x_range), y=(y_range)), streams=[range_stream])
datashade(points, streams=[range_stream]) + dyn_hist
```

**Comment by jbednar** [comment]
Thanks, @philippjfr. Output from your first code example above, at different zooms:

![image](https://user-images.githubusercontent.com/1695496/41384313-9da6929a-6f3a-11e8-99ec-9c2ed9cd5582.png)
![image](https://user-images.githubusercontent.com/1695496/41384319-adf17fca-6f3a-11e8-984a-139baec40ad1.png)
![image](https://user-images.githubusercontent.com/1695496/41384328-bbeea7d8-6f3a-11e8-9b4e-2f55dc98708e.png)

**Comment by rtmatx** [comment]
Hi,

Thank you @philippjfr for the comment and the code. I tried to use the code on a dataframe to see how the histogram changes with the selection of the data on the plot to the left. 

I am having trouble with the histogram on the right as it is just showing uniform values when there is at least two modes and also the values just look incorrect as there no observation around y-value of -200[
![Plot on the dataframe](https://user-images.githubusercontent.com/23462596/41562336-e5b7ba84-7311-11e8-850b-69efa72f05ab.png)
](url)

**Comment by philippjfr** [comment]
Apologies @rtmatx you probably need to enable rescaling of the axis for the histogram like this:

```python
points = hv.Scatter(df, 'id_', 'col_')
rasterized = rasterize(points, aggregator='mean')
rasterized.hist(dimension='col_').map(shade, hv.Image).options('Histogram', framewise=True)
```

**Comment by rtmatx** [comment]
Thanks @philippjfr. I tried with the above code and got an error. I have pasted the error stack here. Looks like few ipython functions are not able to process it. 

```
TypeError                                 Traceback (most recent call last)
<ipython-input-71-13d33c392405> in <module>()
      9 points = hv.Scatter(temp, 'id_', 'col_')
     10 rasterized = rasterize(points, aggregator='mean')
---> 11 rasterized.hist(dimension='col_').map(shade, hv.Image).options('Histogram', framewise=True)

~/anaconda/envs/m/lib/python3.6/site-packages/IPython/core/displayhook.py in __call__(self, result)
    255             self.start_displayhook()
    256             self.write_output_prompt()
--> 257             format_dict, md_dict = self.compute_format_data(result)
    258             self.update_user_ns(result)
    259             self.fill_exec_result(result)

~/anaconda/envs/m/lib/python3.6/site-packages/IPython/core/displayhook.py in compute_format_data(self, result)
    149 
    150         """
--> 151         return self.shell.display_formatter.format(result)
    152 
    153     # This can be set to True by the write_output_prompt method in a subclass

~/anaconda/envs/m/lib/python3.6/site-packages/IPython/core/formatters.py in format(self, obj, include, exclude)
    148             return {}, {}
    149 
--> 150         format_dict, md_dict = self.mimebundle_formatter(obj, include=include, exclude=exclude)
    151 
    152         if format_dict or md_dict:

TypeError: 'NoneType' object is not iterable
```

I tried to check the values of some of the variables in the stack. The `obj` , `result` values in the error stack is 
```
obj :AdjointLayout
   :DynamicMap   []
   :DynamicMap   []
```

**Comment by philippjfr** [comment]
Is there any more to that traceback? It would also be helpful to know which versions of holoviews and IPython you have.

**Comment by rtmatx** [comment]
Holoviews is `1.10.2` and ipython version is `6.2.1`. That is the traceback for this error. Didn't truncate any portion of it.

**Comment by philippjfr** [comment]
Could you try updating to holoviews 1.10.5? I can't reproduce the issue.

**Comment by rtmatx** [comment]
I updated holoviews to 1.10.5 but I got the same error stack. I was wondering if there is anything wrong in the dataset as I was looking at this error 
```
DataError: None of the available storage backends were able to support the supplied data format. XArrayInterface raised following error:

 cannot create a Dataset from a DataArray with the same name as one of its coordinates
```

**Comment by rtmatx** [comment]
I was able to create the histograms using the raw data. I noticed that `dyn_hist` doesn't actually calculate the frequencies of the selected but just scales the earlier histogram plot. Is that supposed to be like that

**Comment by rtmatx** [comment]
I couldnt reproduce the issue with recent update and it works with the mentioned code. Thanks @philippjfr
