### ISSUE TITLE
conda env create --file environment.yml gives HTTP CONNECTION ERROR

### ISSUE THREAD

**Issue by vineeshvs** [pyviz/datashader#629]
I get the following error while trying the command 

`conda env create --file environment.yml`

```
V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/free/linux-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Read timed out. (read timeout=9.15)",))',),)

A reportable application error has occurred. Conda has prepared the above report.

```

  * What went wrong, or what were you unable to do?

  * What did you expect to happen?

  * A screen shot, short screen cast, or sketch.

## Errors and warnings

If relevant, please include:

  * Python tracebacks and/or warnings.

  * Any messages/tracebacks in your browser's developer tools console.

## How to reproduce

Ideally, please include a complete, minimal, self-contained python script or notebook that reproduces the issue (in the environment you describe below). http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports contains useful guidance on doing this if you are unsure.

## Your environment

If your version of datashader is neither the latest release (https://github.com/bokeh/datashader/releases/latest) nor the latest GitHub master, please consider upgrading before filing your issue.

Please tell us how to reproduce your environment:

  * If using conda, the output of `conda list` and `conda info`. 

  * If using pip, the output of `pip freeze`.

  * What operating system and version?

  * If relevant, which browser and version?

**Comment by vineeshvs** [comment]
I had solved part of the issue by 
`$ sudo ufw reset`

But stil I am getting the following error while running `conda env create --file environment.yml`

```
Solving environment: failed
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'conda.anaconda.org\', port=443): Max retries exceeded with url: /conda-forge/noarch/repodata.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'conda.anaconda.org\', port=443): Read timed out. (read timeout=9.15)",))',),)

```

**Comment by jbednar** [comment]
That sounds like an internet connectivity issue rather than anything to do with datashader.  To verify, try pointing your browser to https://repo.anaconda.com ; I would assume that you can't see that, in which case no conda commands will work for you...

**Comment by ceball** [comment]
I agree with the previous comment.

You could also try `conda env create -vvv --file environment.yml` to help pinpoint the spot where things 
fail.

I'm going to close this issue because it's not specific to datashader. However, I'm happy to help you debug things, so please feel free to keep replying here.
