### ISSUE TITLE
module 'datashader.transfer_functions' has no attribute 'interpolate'

### ISSUE THREAD

**Issue by WillManidis** [pyviz/datashader#637]
Currently have version `0.6.6 `installed, and getting a weird error. On running any code that includes 
`tf.interpolate()` I receive the error 

`AttributeError: module 'datashader.transfer_functions' has no attribute 'interpolate'`

and importing as `import datashader.transfer_functions as tf`

**Comment by jbednar** [comment]
tf.interpolate is no longer supported; please use tf.shade().  tf.shade() is the result of mergint tf.colorize and tf.interpolate, but because there were small API differences between shade and the predecessors, the predecessors are no longer available.
