### ISSUE TITLE
Additionally re-run (some part of) the test suite without numba

### ISSUE THREAD

**Issue by ceball** [pyviz/datashader#646]
E.g. there are no bounds checks for array indexing in numba.

Doing this task would require tests that are feasible to run without numba.

**Comment by stuartarchibald** [comment]
This may help http://numba.pydata.org/numba-doc/dev/reference/envvars.html#envvar-NUMBA_DISABLE_JIT ?

**Comment by jbednar** [comment]
That's helpful, thanks!

**Comment by ceball** [comment]
Can you also suggest a way to make things run fast enough with numba disabled so that we don't have to alter the test suite? ;)

**Comment by jbednar** [comment]
Done!
