### ISSUE TITLE
Handle categorical columns correctly on dask dataframes

### ISSUE THREAD

**Issue by philippjfr** [pyviz/datashader#653]
In https://github.com/pyviz/datashader/pull/634 we discovered that when loading data using dask, categorical columns are not necessarily handled correctly. Specifically the code currently calls ``.head()`` to load the categories into memory, but this only works correctly for parquet files written with fastparquet, for other data sources the categories can only reliably be computed by loading the whole column into memory.

The appropriate solution is to ensure that ``categorize`` or ``as_known`` are called on the categorical columns before aggregation. However this can cause significant slowdowns in many scenarios so we have to carefully consider how best to go about implementing this, i.e. consider some caching strategy or strongly suggest that users run this beforehand to ensure that the categories do no have to be inferred on every aggregation.

**Comment by jbednar** [comment]
Agreed.  So the current situation is that with fastparquet files, the results will be fast, but other parquet files will fail to load properly?  Sounds like do need to address that after this coming release, then.

**Comment by philippjfr** [comment]
>So the current situation is that with fastparquet files, the results will be fast, but other parquet files will fail to load properly?

The situation is that the code that tries to infer categories might fail to detect all existing categories unless the data is loaded from a parquet file which was written using fastparquet, which stores the available categories in the metadata. To guarantee correct behavior we would always have to load the entire column into memory to find the unique categories.
