### ISSUE TITLE
Spatially partitioned data structures

### ISSUE THREAD

**Issue by jbednar** [pyviz/datashader#678]
Right now, Datashader iterates through the entire dataset each time it computes an aggregation of points, lines, or trimesh grids.  This approach allows Datashader to use standard Pandas and Dask dataframes, but it has the major disadvantage that repeated aggregations over a tiny subset of the data (e.g. census data from NYC) are just as expensive as for the full data (e.g. the entire US census data), which makes interactive zooming much slower than it needs to be.

Various [spatial data structures](https://blog.mapbox.com/a-dive-into-spatial-search-algorithms-ebd0c5e39d2a) have been defined that divide the data into spatial subsets for efficient access, such as [RTrees](https://geoffboeing.com/2016/10/r-tree-spatial-index-python) and [KDTrees](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.spatial.KDTree.html), and it would be great to add optional support for one of these to Datashader.

![image](https://user-images.githubusercontent.com/1695496/50648418-c7726f80-0f40-11e9-9e58-7e6204870464.png)

**Comment by jonmmease** [comment]
Done in #702 and #706
