### ISSUE TITLE
Numba JIT caching does not work when using dask distributed scheduler

### ISSUE THREAD

**Issue by philippjfr** [pyviz/datashader#684]
When using datashader using dask distributed it seems like the numba JIT does not work correctly and there is a large overhead from having to recompile the aggregation kernels every time an aggregation occurs adding 0.5-1 second of overhead.

```python
import distributed
import dask.dataframe as dd
import holoviews as hv
hv.extension('bokeh')

client = distributed.Client()
client

df = dd.read_parquet('data/nyc_taxi_wide.parq', columns=['pickup_x', 'pickup_y'])
df_partitioned = df.repartition(npartitions=8).persist()

datashade(hv.Points(df_partitioned))
```

If we now look at the dask diagnostics dashboard profiling pane we can see that a huge amount of time is spent on the numba compilation step, which grows every time we zoom.

![screen shot 2019-01-08 at 11 50 22 am](https://user-images.githubusercontent.com/1550771/50829238-b14b2180-133b-11e9-8435-b2800c92c3b4.png)

**Comment by jbednar** [comment]
What numba version is this?  Version 0.40.0 included a relevant addition...

**Comment by philippjfr** [comment]
Sorry, should have noted that and updated to latest. This was with 0.39, I'll repeat with the latest version.

**Comment by philippjfr** [comment]
Can confirm that using latest numba this problem does not occur.
