### ISSUE TITLE
Warning in the nyc_taxi topic notebook

### ISSUE THREAD

**Issue by jlstevens** [pyviz/datashader#686]
Quick issue to note that the following warning is being issued in the nyc_taxi topic notebook (and I've seen the same warning crop up in a few other places as well):

![image 1](https://user-images.githubusercontent.com/890576/51064081-84a93b00-15c3-11e9-836e-ad9c15168ef4.png)

**Comment by jbednar** [comment]
Fixed in https://github.com/pyviz/datashader/pull/697
