### ISSUE TITLE
datashader import

### ISSUE THREAD

**Issue by runkles** [pyviz/datashader#690]
I'm trying to import datashader in Jupyter Notebook and I'm getting following error:
```python   
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-3d7b1ff9e530> in <module>()
----> 1 import datashader

ImportError: No module named datashader
```
I can do the import in IPython in Spyder but not in Jupyter notebook.

Name, Version, Build, Channel
datashader,  0.6.8, py_0, conda-forge

jupyter notebook --version 5.7.2

Any recomendation how to fix it? It worked 10 days ago without a problem.
Thanks

**Comment by runkles** [comment]
Reinstalling datashader fixed the issue.

**Comment by jbednar** [comment]
Usually that means your Jupyter kernel is not running in the environment where datashader is installed.  You may be able to select a different kernel from within Jupyter, or you can install datashader in this different environment (which it seems like you did).
