### ISSUE TITLE
Simpler API for SpatialDataFrame 

### ISSUE THREAD

**Issue by philippjfr** [pyviz/datashader#705]
The new ``SpatialDataFrame`` provides very powerful functionality however there is still some scope for improving the API. Specifically after some discussion we came up with a proposal that will make it very easy to use it in practice.

## Proposal

The core of the proposal is to turn the `SpatialDataFrame` into a subclass of dask's DataFrame itself. By default the `SpatialDataFrame` would behave just like the regular dask DataFrame and the main difference would be twofold:

1) It holds the required metadata to perform the spatial indexing
2) It has a method to return the result of a spatial query

In addition to this subclass we would then have functions to save/load a parquet file with the additional metadata and returns a SpatialDataFrame. The second component then would be for ``canvas.points`` to perform an `isinstance` to check whether the provided DataFrame is a `SpatialDataFrame` and then automatically perform the spatial query using the Canvas' `x_range` and `y_range`.

The major benefit here is that for all other purposes the SpatialDataFrame would work as it does now, and a Canvas could automatically perform the spatial queries. This also means that **no** special handling is required in holoviews.

**Comment by jonmmease** [comment]
@philippjfr, sounds good.  Any preference on what to do with the current properties of SpatialPointsFrame?  (We obviously don't want to take over the `.x` and `.y` properties of a dataframe subclass.)

**Comment by philippjfr** [comment]
Maybe a namedtuple attribute with the necessary metadata. Not convinced about the naming but something like:

```python
sdf.spatial.x
```

**Comment by jonmmease** [comment]
yeah, that's a nice way to 'namespace' these properties. And using a namedtuple will make them immutable for free.

**Comment by philippjfr** [comment]
One thing we didn't think about is what happens when you call a method on this SpatialDataFrame, does it return another SpatialDataFrame, will it lose the metadata that way?

**Comment by jonmmease** [comment]
My preference is to start without any methods preserving the spatial subclass.  If there are compelling reasons to do so later since it would be a non-breaking change (as long as `SpatialPointsFrame` is a faithful subclass of `dd.DataFrame`).  Sounds alright?

**Comment by jonmmease** [comment]
> Maybe a namedtuple attribute with the necessary metadata. Not convinced about the naming but something like:

Oh, but some of the properties are dynamically generated
```python
@property
    def hilbert_distances(self):
        """
        Dask series containing the Hilbert distance of each row in frame

        Returns
        -------
        dd.Series
        """
        x = self.x
        y = self._y
        p = self._p
        x_range = self._x_range
        y_range = self._y_range
        return self._frame.map_partitions(
            _compute_distance, x=x, y=y, p=p,
            x_range=x_range, y_range=y_range)
```

maybe I'll add a `spatial_` prefix to the properties...

**Comment by jonmmease** [comment]
Done in #706 with a few loose ends being wrapped up in #708
