### ISSUE TITLE
Interactive Datashader + Holoviews Plot does not Update in VSCode

### ISSUE THREAD

**Issue by fedario** [pyviz/datashader#739]
## Description

When plotting interactively using Datashader and Holoviews it does not update the data shading when zooming in.
This is only the case when plotting via a Jupyter session in VSCode. It works when using a standalone Jupyter session.

Here is the code I have used:

```Python
# %%
import os
import datashader as ds
import pandas as pd
from colorcet import fire
from datashader import transfer_functions as tf
import holoviews as hv
import geoviews as gv
from holoviews.operation.datashader import datashade
hv.extension("bokeh")

data_path = os.path.expanduser("~/Downloads/test_data/nyc_taxi.csv")

df = pd.read_csv(
    data_path,
    usecols=["dropoff_x",  "dropoff_y"],
)

agg = ds.Canvas().points(df, "dropoff_x", "dropoff_y")
tf.set_background(tf.shade(agg, cmap=fire), "black")

url = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}.jpg"
tile_opts = dict(
    width=1000,
    height=600,
    xaxis=None,
    yaxis=None,
    bgcolor="black",
    show_grid=False,
)
map_tiles = gv.WMTS(url).opts(style=dict(alpha=0.5), plot=tile_opts)
points = hv.Points(df, ["dropoff_x", "dropoff_y"])
taxi_trips = datashade(
    points,
    x_sampling=1,
    y_sampling=1,
    cmap=fire,
    width=1000,
    height=600,
)

map_tiles * taxi_trips
```

## Environment (truncated)

OS: Ubuntu 18.04

VSCode version: 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8 x64)

```
# Name                    Version                   Build  Channel
anaconda                  2019.03                  py37_0  
bokeh                     1.0.4                    py37_0  
colorcet                  2.0.1                      py_0    pyviz
conda                     4.6.11                   py37_0  
conda-build               3.17.8                   py37_0  
conda-env                 2.6.0                         1  
conda-verify              3.1.1                    py37_0  
datashader                0.6.8                      py_0    pyviz
geos                      3.7.1                he6710b0_0  
geoviews                  1.6.2                      py_0    pyviz
geoviews-core             1.6.2                      py_0  
holoviews                 1.11.0             pyh39e3cac_0    pyviz
hvplot                    0.4.0                      py_0    pyviz
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.4.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.2                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.4.0                    py37_0  
jupyterlab                0.35.4           py37hf63ae98_0  
jupyterlab_server         0.2.0                    py37_0  
python                    3.7.3                h0371630_0  
```

**Comment by jbednar** [comment]
Thanks for filing the issue and including all the details!  This problem isn't specifically related to Datashader; Datashader doesn't know whether it's being called for the initial render or when zooming in, and if it works initially that means Datashader itself is fine.  In HoloViews, the difference between the initial render and zooming is that zooming requires communication from JS back to Python. It sounds like that's not working for you, which might be fixed if you upgrade to HoloViews 1.12, because of the changes in https://github.com/pyviz/holoviews/pull/3574.  If that doesn't fix it, please open a new issue on the [HoloViews repository](https://github.com/pyviz/holoviews/issues) describing what happens for the current HoloViews version.

**Comment by philippjfr** [comment]
It is quite unlikely this will ever work. Communication between JS and python requires a live websocket. It may be possible to get this working by embedding a bokeh server but the usual notebook display machinery in VSCode does not support websocket comms afaik.

**Comment by KestutisMa** [comment]
it works now with panel.extension(comms='vscode')

**Comment by peterroelants** [comment]
> it works now with panel.extension(comms='vscode'), can close issue

I still seem to be running into issues with datashaded plots.

**Comment by peterroelants** [comment]
> I still seem to be running into issues with datashaded plots.

It seems more like a very inconsistent experience, sometimes it works and sometimes it does not. If it doesn't work then restarting VSCode seems to solve it from time to time.

**Comment by jbednar** [comment]
Please open a issue with the full details on the repository for whatever tool you are using (presumably hvPlot, HoloViews, or Plotly); this is unlikely to be an issue with Datashader itself.
