### ISSUE TITLE
Import datashader in Jupter notebook with Python 3.5 kernel hangs cell.

### ISSUE THREAD

**Issue by akum036** [pyviz/datashader#749]
## Description

If install a fresh Python 3.5.2 environment with just Jupyter and Datashader (with dependencies), then try and import Datashader in the notebook, the notebook hangs in any cells run after the datashader import.

This does not happen when running from an ipython terminal or if using Python 3.7

## How to reproduce

From the CLI:
`python 3.5 -m venv venv`
`. venv/bin/activate`
`pip install jupyter datashader`
`jupyter notebook`

In the notebook:
`import datashader` - Cell 1

`print('hello')` - Cell 2

The `print('hello')` command will not complete after Cell 1 has finished running. No warnings are given.
## Errors and warnings

Looking at the debug output of the terminal when running the notebook, the pattern of status, execute_input and stream is broken, the execute_inpu part doesn't run again.

## Your environment
Ubuntu 16.04
Python 3.5.2
Firefox 66.0.5

attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
bokeh==1.1.0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
cloudpickle==1.1.1
colorcet==2.0.1
cycler==0.10.0
dask==1.2.2
datashader==0.7.0
datashape==0.5.2
decorator==4.4.0
defusedxml==0.6.0
distributed==1.28.1
entrypoints==0.3
HeapDict==1.0.0
idna==2.8
imageio==2.5.0
ipykernel==5.1.1
ipython==7.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.13.3
Jinja2==2.10.1
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
kiwisolver==1.1.0
llvmlite==0.28.0
locket==0.2.0
MarkupSafe==1.1.1
matplotlib==3.0.3
mistune==0.8.4
msgpack==0.6.1
multipledispatch==0.6.0
nbconvert==5.5.0
nbformat==4.4.0
networkx==2.3
notebook==5.7.8
numba==0.43.1
numpy==1.16.3
packaging==19.0
pandas==0.24.2
pandocfilters==1.4.2
param==1.9.0
parso==0.4.0
partd==0.3.10
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.0.0
pkg-resources==0.0.0
prometheus-client==0.6.0
prompt-toolkit==2.0.9
psutil==5.6.2
ptyprocess==0.6.0
pyct==0.4.6
Pygments==2.4.0
pyparsing==2.4.0
pyrsistent==0.15.2
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
PyYAML==5.1
pyzmq==18.0.1
qtconsole==4.4.4
requests==2.22.0
scikit-image==0.15.0
scipy==1.3.0
Send2Trash==1.5.0
six==1.12.0
sortedcontainers==2.1.0
tblib==1.4.0
terminado==0.8.2
testpath==0.3.1
toolz==0.9.0
tornado==6.0.2
traitlets==4.3.2
urllib3==1.25.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2
xarray==0.12.1
zict==0.1.4

**Comment by jbednar** [comment]
Hmm. According to our website,  "Datashader supports Python 2.7, 3.5, 3.6 and 3.7", but I only see tests being run for 2.7 and 3.6.  Presumably we shouldn't be claiming 3.5 and 3.7 support without tests running!  That said, it's very strange that there would be problems in Jupyter that don't appear in plain IPython, as Datashader doesn't install any Jupyter-related extensions or other code that's specific to Jupyter, at least not until actually displaying some output in Jupyter.  We'll have to see if we can reproduce the problem, and also see if we can set up some tests on 3.5 and 3.7.

**Comment by akum036** [comment]
I've done some further digging and it looks like the issues stems (at least) from importing xarray. A clean environment with only Jupyter and xarray seems to work fine.

**Comment by jsignell** [comment]
I am experimenting with running tests using other versions of python. I noticed though that the distribution team is not building conda 4.6 for python 3.5. Do we really want to be supporting python 3.5 still? If so I'll need to figure out how to get around the errors in https://travis-ci.org/pyviz/datashader/jobs/535321978

**Comment by jbednar** [comment]
I don't have much opinion about 3.5; I don't personally know any person or project that relies on it (apparently other than @akum036 :-). But I do know that we should either remove the claim that we support 3.5, or start testing against it.  Having no conda support for 3.5 tilts the balance towards not supporting 3.5; is there anything tilting the other way?

**Comment by jsignell** [comment]
I don't have anything to tilt towards supporting 3.5. @akum036 do you have a reason why you can't use 3.6 or 3.7?

**Comment by akum036** [comment]
We use 3.5 as it's the default in Ubuntu 16.04 LTS.

**Comment by jbednar** [comment]
Ugh!  Looks like Ubuntu chose a Python release that was already four years old (3.5 released 2015) for their 2/2019 16.04 LTS release, and now users are stuck with that for the next three years, even though 3.6 was already available in 2016.  I guess they only care about sysadmin tasks, where the Python version doesn't matter?

I'd personally not encourage ever using the system Python for doing data science, so I'm not inclined to go out of our way to try to get 3.5 working given the lack of conda support.  I can be convinced, but it's annoying and will slow down all our tests...



3.5 (from 2015!) for an LTS release from 2/2019.  They're 


Python 3.6 was released in 2016, yet 


Looks like that was released in 2/2019, and so will be with us for 3 years, which is annoy


.  That's a shame, given that Python 3.6 was released in 2016, meaning 


I guess Ubuntu doesn't much care what Python version is used, as it's mainly for sysadmin tasks and they'd rather not have

**Comment by akum036** [comment]
Fair enough. I'll close the issue assuming you'll remove 3.5 as a supported version from the documentation.

**Comment by jbednar** [comment]
Ok, thanks.  @jsignell, please remove 3.5 from the PR unless you see a simple way to fix the 3.5 tests.
