### ISSUE TITLE
Add option to `datashader examples` to download specific dataset

### ISSUE THREAD

**Issue by dharhas** [pyviz/datashader#753]
## Description

Currently running the cli command `datashader examples` downloads all the example datasets that are available. This can take a fairly long time and is unnecessary if you only plan to use one or two of the datasets. 

I propose we add a new options to the cli command that lets us list and specify the datasets we want to download.

i.e.

`datashader examples --list`: list the available datasets
`datashader examples -d nyc-taxi census`: downloads the nyc-taxi and census datasets & associated notebooks

(We might want to use different flags than the ones above)

**Comment by jbednar** [comment]
We've moved all the Datashader topic examples to https://github.com/pyviz-topics/examples, where each topic is set up as an independent anaconda-project, fully reproducible on its own and fetching its own dataset. It's not released yet, but soon!  For the next Datashader release, only the datasets used in the actual docs (not much) will be fetched with the examples.
