### ISSUE TITLE
change `calculate_zoom_level_stats` in tiles.py to use np.nanmin() / np.nanmax()

### ISSUE THREAD

**Issue by EtsuNDmA** [pyviz/datashader#758]
When I use example from [tiling.ipynb](https://github.com/pyviz/datashader/blob/master/examples/tiling.ipynb) but modify rasterize func to use the other reduction 
```python
from datashader.reductions import sum as sum_reduction
def rasterize_func(df, x_range, y_range, height, width):
    cvs = ds.Canvas(x_range=x_range, y_range=y_range, plot_height=height, plot_width=width)
    agg = cvs.points(df, 'x', 'y', agg=sum_reduction)
    return agg
```
function `calculate_zoom_level_stats` calls  `_get_super_tile_min_max` for each supertile and `_get_super_tile_min_max` returns `(agg.data.min(), agg.data.max())`. If agg.data has nan's, the result will be all nan's

I expect `_get_super_tile_min_max` to return `(np.nanmin(agg.data), np.nanmax(agg.data))` like transfer_sunctions.shade do when calculate span

**Comment by brendancol** [comment]
@EtsuNDmA Thanks for report this issue!  I will take a look a ping when updated.  If you've monkey patched it on your side feel free to submit a PR, else I'll ping back when a fix is commited.  Thanks again.
