### ISSUE TITLE
large category number

### ISSUE THREAD

**Issue by drmatthews** [pyviz/datashader#767]
Apologies if I am not posting this in the correct place, but I'm looking for some help with using datashader for plotting points clustered using DBSCAN. Each cluster has an ID and I would like to colourise each cluster according to its ID. The data is in a Pandas DataFrame and ID column has dtype set to 'category'. Each cluster has a modest number of points but there are typically >500 clusters (the total number of points can be around 1e6) which means >500 different categories.

I am trying to use Holoviews to produce and interactive plot and the bit of code that does the plotting is:

```
points = hv.Points(clusters, kdims=['x', 'y'], vdims=['cluster_id'])

dynspread(datashade(points, aggregator=ds.count_cat('cluster_id')).opts(width=400, height=400))
```

This works when the number of clusters is small but fails when I try the full data set:

ValueError: Insufficient colors provided (22) for the categorical fields available (573)

I have tried making a color_key but the datashader colours all seem to have length 256. I tried to interpolate a Matplotlib colour map over all 500 cluster_ids and the code above runs but each point is black (or grey when I zoom).

I'm sure I've missed (or misunderstood) something in the docs so sorry to waste your time if there is a trivial solution.

Thanks!

Dan.

**Comment by jbednar** [comment]
Colorcet.pyviz.org offers 256-color [categorical colormaps](http://colorcet.pyviz.org/user_guide/Categorical.html), and if you need more, you can always concatenate them: `import colorcet as cc ; long_key = list(set(cc.glasbey_cool +  cc.glasbey_warm + cc.glasbey_dark)); datashade(..., color_key=long_key)`. You can also use the `glasbey` python package to make sets of colors of any length. Either way, you'll get a plot where every category has a different color, but humans are not good at discriminating between so many similar colors, so I would recommend trying to add some hierarchical structure to the categories and then use colors per category in separate plots, or some other way to make the data actually understandable.
