### ISSUE TITLE
Modin Pandas

### ISSUE THREAD

**Issue by mccarthyryanc** [pyviz/datashader#770]
Datashader currently requires pandas or dask dataframes. It would be nice to use [modin](https://modin.readthedocs.io/en/latest/index.html) pandas. This way you can use Ray or Dask for distributing work.

It looks like many of the [DataFrame methods](https://modin.readthedocs.io/en/latest/UsingPandasonRay/dataframe_supported.html) used in Datashader are already available.

**Comment by jbednar** [comment]
Thanks. Does Modin+Ray offer a clear benefit over the existing Dask support?  E.g. are there cases where Ray greatly outperforms Dask, or is usable on systems Dask isn't, or something similar?  If so it would be great to have Ray support via Modin.

**Comment by mccarthyryanc** [comment]
Sorry for the slow reply. The current Dask support is great and I'm not sure modin offers any better performance or usability. However, Ray abstracts out the distribution pieces, [autoscaling](https://ray.readthedocs.io/en/latest/autoscaling.html) for example. Making it really simple to move code to a cluster, without worrying about starting/stopping workers.

**Comment by jbednar** [comment]
I haven't used it myself, but I've seen Dask used with autoscaling throughout the [ppangeo.io](http://pangeo.io) project, so it sounds like they are also similar in that respect.  I'll close this for now, but if anyone outlines a specific case where Ray/Modin would provide a major benefit, we can certainly reopen it!
