### ISSUE TITLE
Legend order - datashade scatter plot

### ISSUE THREAD

**Issue by dovz11** [pyviz/datashader#773]
## Description

I am plotting a scatter plot of a large data set.  

The relevant columns include an X, Y as well as another field (will call it'description_field' here) which influence the color of the resulted point.  I get the right legend when plotting without a datashder.  

When using datashader (directly from hvplot or through the datashader APIs), I am following the suggestions [here](http://datashader.org/getting_started/3_Interactivity.html) and [here](http://holoviews.org/user_guide/Large_Data.html) advising how to manually create and overlap a legend.  The method is working however, I am unable to contract the right order of legend text description.  I am generating the description from the description dataframe column using df['description_field'].unique()

Any suggestion for how to get legend description in the same order used by datashader?
Thanks in Advance,
Dov

**Comment by jbednar** [comment]
Without the code involved it is very difficult to see what the problem is. It sounds like you are wanting a color key, and the ordering of the colors in the key is not matching the ordering in the plot? If so, I would recommend using a dictionary for the Datashader color_key and for creating the legend. Datashader accepts either a list or a dictionary, with the list being the default, but the list only implicitly maps colors to categories; the dictionary lets you explicitly assign a color to each category in a way that ensures you don't get confused when creating the legend.

**Comment by dovz11** [comment]
Thanks you.  I made some progress and able to get datashade the use  the same color key I am displaying as legend.  My problem now is that I am not able to overlay the legend on top of the scatter plot.  Below is the relevant code and output.  Any suggestions/corrections:

`pm.shape`
(95997, 3)
`pm.head(1)`

venergyTotal_kWh | current_A |recipe 
 -- | -- | -- 
8053.753623 | 83.78 | NA

```
import holoviews as hv
import holoviews.operation.datashader as hd
from holoviews.operation.datashader import datashade, shade, dynspread, rasterize
import datashader as ds
hd.shade.cmap=["lightblue", "darkblue"]
hv.extension("bokeh")
from datashader.colors import Sets1to3

color_key = [(name,color) for name,color in zip(pm['recipe'].unique(), Sets1to3)]
color_points = hv.NdOverlay({n: hv.Points([0,0], label=str(n)).opts(style=dict(color=c)) for n,c in color_key})
colorDict = {n:c for n,c in color_key}
```
```
a=hv.Scatter(pm, kdims=['venergyTotal_kWh'], vdims=['current_A', 'recipe'])
gb=a.groupby('recipe')
ol=gb.overlay()
ol.opts(width=800, height=400)
```
![image](https://user-images.githubusercontent.com/25162479/62154584-dbeece80-b2bb-11e9-8721-767cddffcae8.png)
```
sctr = dynspread(datashade(ol,aggregator=ds.count_cat('recipe'),color_key=colorDict))
sctr.opts(width=800, height=400)
```
![image](https://user-images.githubusercontent.com/25162479/62154680-10628a80-b2bc-11e9-8422-73678b0810ad.png)
`sctr * color_points`
![image](https://user-images.githubusercontent.com/25162479/62154737-35ef9400-b2bc-11e9-98df-7c5079c2a1cc.png)

**Comment by jbednar** [comment]
Pretty!  Here the fake `color_points` key is specified to be located at [0,0]; you should use a location that's in the viewport of your plot (something contained in the x and y axis ranges). With 0,0 as above, your real data is all in the upper right, but once you put the key at a suitable location you should be able to see your data fine.

**Comment by dovz11** [comment]
Thanks.  Thank solve the issue
