### ISSUE TITLE
Spatial tools next steps

### ISSUE THREAD

**Issue by brendancol** [pyviz/datashader#784]
### Implement before next release
- [x] fix issue with viewshed observer distance +/+ quadrant
- [x] more robust viewshed tests
- [x] more robust zonal tests
- [ ] other docs besides user guide?

### Nice to have
- [x] further viewshed numba optimizations
- [ ] add ellipsoid great circle distance (this may currently be inside of viewshed code)...
- [ ] add tabulate area example using custom stat function
- [ ] add proximity polygon example when polygons are merged

**Comment by jbednar** [comment]
It seems like some of those are required (e.g. tests and fixes) and others are optional future work (e.g. ellipsoid great circles).  Can you mark the optional ones so that it's clear when we can consider releasing?

**Comment by brendancol** [comment]
@jbednar what about breaking out functions from `datashader/geo.py` module into individual modules in `datashader/spatial/{hillshade, slope, etc.}.py` with the idea that anything `geo` is technically a type of `spatial`

**Comment by jbednar** [comment]
Moving to datashader.spatial makes sense to me, but I'm not sure what the motivation for further subdividing it -- do those routines have a lot of code?  do they have special dependencies?  If not, I'd default to one module, not many.

**Comment by brendancol** [comment]
@jbednar most of these items have been addressed and this issue has become stale. I'm going to close it and then we can re-open separate issues as they come up
