### ISSUE TITLE
Future and Deprecation warnings

### ISSUE THREAD

**Issue by philippjfr** [pyviz/datashader#789]
There's at least two warnings being raised from datashader right now:

```
datashader/transfer_functions.py:21: FutureWarning: xarray subclass Image should explicitly define __slots__
  class Image(xr.DataArray):

datashader/bundling.py:325: FutureWarning: The 'get_values' method is deprecated and will be removed in a future version. Use '.values' or 'np.asarray(..)' instead.
```

**Comment by jbednar** [comment]
Looks like those are new deprecations from xarray and pandas, respectively:

http://xarray.pydata.org/en/stable/whats-new.html#v0-13-0-17-sep-2019

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.get_values.html

I'll see if I can make a PR to update our usage of those features.
