### ISSUE TITLE
Pyct requirement causing error

### ISSUE THREAD

**Issue by Mulan-94** [pyviz/datashader#820]
## Description
Hi guys, 
Datashader throws and error through pkg.resources because of a dependency pyct. The error comes about when trying to launch a package that depends on datashader and is:

```
Traceback (most recent call last):
  File "/home/ragEnv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests; extra == "cmd"' distribution was not found and is required by pyct

```
Re-installing `pyct` as `pyct[cmd]` seemed to do the trick.
This was on:
```
Python 3.6.8 (in virtualenv)
Ubuntu 18.04.2
Pip 19.3.1
Datashader 0.8.0
```
Thank you so much for this project!

**Comment by ceball** [comment]
How did you install datashader? Its setup.py lists pyct[cmd] as a dependency.

**Comment by jbednar** [comment]
The question is, _precisely_ how did you install it?  The pip setup appears to indicate that if you did the normal `pip install datashader`, then it should have installed `pyct[cmd]` already, in which case we must have a bizarre bug in our setup or pip is somehow failing. But if you did some other installation command, maybe it's just something about what options you passed to pip.

**Comment by Mulan-94** [comment]
Hi @jbednar,
Yes it was through a requirements file with `datashader` as a dependency. I now realize it could be because of another dependency that this happened. My apologies.
